### ISSUE TITLE
Incorrect (?) code generation for trailing function calls

### ISSUE THREAD

**Issue by RalfJung** [tchajed/goose#24] opened 2021-09-06 22:30 UTC
While looking at the "gold test" diff of my follow-up to https://github.com/tchajed/goose/pull/23, I found the following interesting behavior:
```go
func mkInt() uint64 {
	return 42;
}

func mkNothing() {
	mkInt()
}
```
translates to
```go
Definition mkInt: val :=
  rec: "mkInt" <> :=
    #42.

Definition mkNothing: val :=
  rec: "mkNothing" <> :=
    mkInt #().
```
I think this is wrong, since it makes `mkNothing` return 42 when it should return unit. (My refactor fixes this, but that causes a rather large diff.)

Or is there some reason why this is okay to translate the code like this (such as the Go type system preventing us from using that return value anyway -- not sure if we want to rely in that)?

**Comment by tchajed** [comment] 2021-09-06 22:33
This is a duplicate of #15.

**Closed by tchajed** 2021-09-06 22:33 UTC

**Comment by upamanyus** [comment] 2021-09-06 22:35
I think this is the same as #15.

Even if the Go type system prevents us from using the return value, we probably would want to prove something about a function like `mkNothing`, at which point in time with the incorrect translation, the Perennial spec would need to say that a non-unit value is returned.
